name: get-applications-vic
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "1 21 * * 0"
jobs:
  scraper:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Check out this repo
        uses: actions/checkout@v2

      - name: set timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Australia/Melbourne"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install pipenv
        run: python -m pip install pipenv

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_WHERE_AM_I: ${{ secrets.WHERE_AM_I}}
          envkey_OUTPUT_DIRECTORY: ${{ secrets.OUTPUT_DIRECTORY}}
          envkey_OUTPUT_FILENAME: ${{ secrets.OUTPUT_FILENAME}}
          envkey_BLOB_CONTAINER_NAME: ${{ secrets.BLOB_CONTAINER_NAME}}
          envkey_BLOB_CONNECTION_STRING: ${{ secrets.BLOB_CONNECTION_STRING}}
          fail_on_empty: true

      - name: Install dependencies
        run: pipenv install --deploy --dev

      - name: Run script
        run: |
          pipenv run python liquor_licence_applications_vic_scrape.py
